plugins {
    id 'java'
    id 'io.qameta.allure' version '2.12.0'
}

group = 'ru.random783'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

def restAssuredVersion = "6.0.0",
    allureVersion = "2.32.0",
    junitVersion = "5.14.3",
    slf4jVersion = "2.0.17"

allure {
    report {
        version.set(allureVersion)
    }
    adapter { // отвечает за появление папочки build/allure-results
        aspectjWeaver.set(true) //обработка аннотации @Step
        frameworks {
            junit5 { //название фреймворка
                adapterVersion.set(allureVersion) //версия интеграции фреймворка и Allure
            }
        }
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation("org.junit.jupiter:junit-jupiter",
            "io.rest-assured:rest-assured:$restAssuredVersion",
            "io.rest-assured:json-schema-validator:$restAssuredVersion",
            "tools.jackson.core:jackson-databind:3.1.0",
            "org.assertj:assertj-core:3.27.7",
            "io.qameta.allure:allure-rest-assured:$allureVersion",
            "com.codeborne:selenide:7.14.0",
            "org.slf4j:slf4j-simple:2.0.7",
            "net.datafaker:datafaker:2.7.0",
            "io.qameta.allure:allure-selenide:$allureVersion")
}
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
tasks.withType(Test) {
    useJUnitPlatform()
    systemProperties(System.getProperties())
    testLogging {
        lifecycle {
            events "started", "skipped", "failed", "standard_error", "standard_out"
            exceptionFormat "short"
        }
    }
}